### ISSUE TITLE
No module named 'nonebot.adapters.cqhttp

### ISSUE THREAD

**Issue by shenvinci** [Zeta-qixi/nonebot-plugin-covid19-news#1]
使用插件的时候报错No module named 'nonebot.adapters.cqhttp，请问这个库是在哪里的呀

**Comment by Zeta-qixi** [comment]
是旧版本nonebot2的库，这次更新库没了。这个仓库的插件库是nonebot 2.0.0a16环境。
这周末我看看新的nonebot用什么

**Comment by Zeta-qixi** [comment]
把`cqhttp`改为对应你使用的adapters就好了，比如`nonebot.adapters.onebot.v11`

**Comment by Zeta-qixi** [comment]
> 使用插件的时候报错No module named 'nonebot.adapters.cqhttp，请问这个库是在哪里的呀

已经将新版本上传（0.2.2）

**Comment by shenvinci** [comment]
好嘞，谢谢呀
