### ISSUE TITLE
加载插件出现问题

### ISSUE THREAD

**Issue by HuParry** [Zeta-qixi/nonebot-plugin-covid19-news#10]
我加载插件，出现了如图所示的错误。
TypeError: unsupported operand type(s) for +: 'int' and 'str'
![O( P8G{99RYIU_GS@}1IR%9](https://user-images.githubusercontent.com/103566602/167246925-4e0a3536-a793-4452-aefb-1fd218dfcbd8.png)

**Comment by Special-Week** [comment]
可能是API被暗改了,tools.py第13行那个改成
try:
            self.wzz_add = int(data['today'].get('wzz_add'))
        except:
            self.wzz_add = 0
就可以运行

**Comment by HuParry** [comment]
已经得到解决，感谢大佬的及时回复！

**Comment by Zeta-qixi** [comment]
已修改，感谢反馈
