### ISSUE TITLE
关注疫情后取消关注失败

### ISSUE THREAD

**Issue by Nana7mij** [Zeta-qixi/nonebot-plugin-covid19-news#11]
关注疫情之后，取消疫情推送回复取消失败

**Comment by Zeta-qixi** [comment]
请问是最新版本吗，可以发一下报错截图？

**Comment by Nana7mij** [comment]
是最新版我用pip下载和本地下载之后上传到服务器上都出现这个问题了，没有报错信息
![图片](https://user-images.githubusercontent.com/91075288/170815496-6600bc11-295f-461c-9321-21ad84ab7916.png)
![图片](https://user-images.githubusercontent.com/91075288/170815540-55e7c033-f8a2-40c0-8e36-cee50906545c.png)

**Comment by Zeta-qixi** [comment]
啊啊 不好意思 readme忘记改了 现在`取消疫情`   `取消关注疫情`

**Comment by Nana7mij** [comment]
o(╥﹏╥)o我这边还是不行，现在加载插件的时候会报一个错，不知道是不是这个原因(原谅我小白不能自己debug o(╥﹏╥)o)
![图片](https://user-images.githubusercontent.com/91075288/170829278-61a1cf52-a83a-4252-8b4d-0384895bfbd1.png)

**Comment by Zeta-qixi** [comment]
更新了新的代码 更新试试。
报错截图截一下上下文

**Comment by Nana7mij** [comment]
抱歉最近期末有点忙拖到现在才回复更新了0.2.9.1版本
报错信息如下
![图片](https://user-images.githubusercontent.com/91075288/171160705-0382eb1f-8e4e-42fc-ab20-72e55ad0edda.png)

**Comment by Zeta-qixi** [comment]
这个应该是`.env.dev`文件设置有问题，可能是和其他插件冲突；已经更新新的代码了，新版本应该就好了。

**Comment by Nana7mij** [comment]
好像是有的，这个要怎么解决呢

**Comment by Zeta-qixi** [comment]
如果你熟悉代码 可以修改插件`__init__.py `55行的代码
`unfollow = on_command("取消关注疫情", priority=5, block=True, aliases={"取消疫情", "取消推送疫情"}) `修改为 不冲突的关键词
