### ISSUE TITLE
取消疫情推送提示失败

### ISSUE THREAD

**Issue by LoCCai** [Zeta-qixi/nonebot-plugin-covid19-news#12]
如题。
data.json文件正常出现群号和城市名，推送信息也正常。

**Comment by Zeta-qixi** [comment]
取消疫情推送的命令改了 `取消疫情`+city。
然后你的bot有没有其他有`取消`触发词的插件？

**Comment by LoCCai** [comment]
***@***.******@***.***


如图，第二个是私聊的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月4日 22:29
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Zeta-qixi/nonebot-plugin-covid19-news] 取消疫情推送提示失败 (Issue #12)


取消疫情推送的命令改了 取消疫情+city。
然后你的bot有没有其他有取消触发词的插件？

―

**Comment by Zeta-qixi** [comment]
参考一下
https://github.com/Zeta-qixi/nonebot-plugin-covid19-news/issues/11

**Comment by LoCCai** [comment]
找到原因了，打印输出了一下：
print(event.get_event_name())
print(gid)
print(event.group_id)
得到了如下结果：

群聊
message.group.normal
QQ号
群号

私聊
message.private.friend
QQ号
AttributeError: 'PrivateMessageEvent' object has no attribute 'group_id'

由此可见：
if event.get_event_name() == 'group'
是此行代码的问题

个人修改如下：
    print(event.get_event_name())
    name=str(event.get_event_name())
    str1="group"
    print(name.find(str1))
    if name.find(str1) == -1:
        gid = str(event.user_id)
    else:
        gid = str(event.group_id)
    print(gid)

**Comment by Zeta-qixi** [comment]
感谢反馈。
这个应该是早期版本，现在已经修复了
`if event.get_event_name() == 'group' :`  改为
 `if "group" in event.get_event_name():  `

建议更新最新版本插件（修复部分bug 和 优化了推送逻辑）
