### ISSUE TITLE
请问能否支持省份的疫情（风险地区）查询

### ISSUE THREAD

**Issue by forchannot** [Zeta-qixi/nonebot-plugin-covid19-news#13]
现在只能查询市级的疫情，查询省份疫情如安徽四川就会报错如图，请问能否支持省份疫情的查询，推送使用合并转发功能来完成推送避免风控
如合并转发[xx省疫情(风险地区)如下:
xx市:
xx市:]每一行代表一个消息，最终合并转发。或者采用制作成图片发送？
![Screenshot_2022-06-05-01-10-33-847_com microsoft rdc androidx](https://user-images.githubusercontent.com/100580891/172018199-22b82e71-3a1a-4d6b-ac3a-72583ffe0b36.png)

**Comment by Zeta-qixi** [comment]
我尝试了一下省份的疫情信息可以查询，报错信息应该是出行政策没有省份（这个确实没有省的 政策都是以市为标准）

省（或直辖市）疫情信息以下级单位的信息合并发送确实可行，感谢意见。

**Comment by forchannot** [comment]
> 我尝试了一下省份的疫情信息可以查询，报错信息应该是出行政策没有省份（这个确实没有省的 政策都是以市为标准）
> 
> 省（或直辖市）疫情信息以下级单位的信息合并发送确实可行，感谢意见。

emmm，好的，我本来的意思就是对于没有出行政策的省份可以查询时直接发送各个市级的信息，如发送四川疫情政策时回复四川各个市级单位的政策并合并转发。
或者是添加问答功能，比如发送四川疫情政策，就会回复列出四川所有可供查询的市级城市，然后回复编号进行查询。
当然，目前的功能也比较充足足够使用了，建议给出的只是锦上添花而已

**Comment by Zeta-qixi** [comment]
原来如此，省内各市的政策，确实有这样的需求。之后会考虑如何实现。

**Comment by forchannot** [comment]
> 原来如此，省内各市的政策，确实有这样的需求。之后会考虑如何实现。

可以检测到用户发送省级单位的时候继续询问，比如检测到某省级风险地区，机器人回复请输入你要查询该省级哪个市的疫情，这时候用户再输入想要查询的市级单位就可以查询。
或者机器人直接回复请输入市级单位进行查询，也可以避免后台报错。
至于检测方法可以用json或者db来储存省级单位信息，每次输入的时候先去这个json里面查找再返回结果
现在输入（省级）风险地区就会报错发不出来

**Comment by Zeta-qixi** [comment]
已经更新这个功能（目前还没测bug

**Comment by forchannot** [comment]
> 已经更新这个功能（目前还没测bug

发送安徽可以了，但是四川，湖南还是会报错，信息如下
