### ISSUE TITLE
数据可能有误差

### ISSUE THREAD

**Issue by bywhales** [Zeta-qixi/nonebot-plugin-covid19-news#14]
![image](https://user-images.githubusercontent.com/95432354/174824359-f6063b85-4646-4849-ba5d-2048d188a4a6.png)
![image](https://user-images.githubusercontent.com/95432354/174824426-7d0b2993-e59e-4391-80f5-bb56c0fea50a.png)

以长沙疫情为例，目前确诊人数存在偏差
希望作者能查看一下

**Comment by Zeta-qixi** [comment]
腾讯的api确实和百度的不一样，在发生近期发生过疫情但已经结束的地区都这样。之后考虑选用不同的api获取信息。

**Comment by Zeta-qixi** [comment]
看了其他不需要申请key的api，没有确诊人数的。可能要看百度会不会发布相关api，或者等腾讯修复一下数据不一致问题。
之前观察过一段时间 至少在新增病例上的数据是一样的，（确诊先无视掉。
