### ISSUE TITLE
上海无法查询风险地区

### ISSUE THREAD

**Issue by LIPiston** [Zeta-qixi/nonebot-plugin-covid19-news#17]
![image](https://user-images.githubusercontent.com/75552696/180985475-191265a6-ea54-4d23-b3e9-221cc4ad45a7.png)

**Comment by Zeta-qixi** [comment]
看一下nonebot和bot的后台输出？

**Comment by Zeta-qixi** [comment]
> 看一下nonebot和bot的后台输出？

https://github.com/Zeta-qixi/nonebot-plugin-covid19-news/issues/15

**Comment by LIPiston** [comment]
nonebot
```
nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed data=None, echo=215,msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
```


go-cqhttp
```
[2022-07-26 23:38:52] [WARNING]: 群消息发送失败: 账号可能被风控.
```
看了说是风控，但是 菏泽风险地区 的能出
![image](https://user-images.githubusercontent.com/75552696/181049693-73f9e703-2e41-4f45-a4b5-d1cae2a6288d.png)

**Comment by Zeta-qixi** [comment]
特定时间的某地的风险地区和疫情出行政策发送会失败，比如现在又出疫情的深圳（两星期前能发送成功），这个问题目前只在是查询一线城市出现，tx不知道搞什么屏蔽。
（图片形式发送在弄了。）

**Comment by Zeta-qixi** [comment]
已更新图片发送功能
