### ISSUE TITLE
似乎不支持emoji

### ISSUE THREAD

**Issue by SnowMoonSS** [Zeta-qixi/nonebot-plugin-covid19-news#20]
![Q7GUNN TG18Y1@I%VGUL{Q](https://user-images.githubusercontent.com/21017431/182551811-5e87f9ce-a053-4bd5-9a83-982c2012bcaa.png)
最前面的红黄绿emoji被渲染成方框了

~~或许可以使用[nonebot-plugin-htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender)来生成图片（这只是一个不会编程的麻瓜的想法~~

**Comment by Zeta-qixi** [comment]
文字图片之后打算分开发送（现在测试文字改颜色效果）
emoji渲染还是麻烦，毕竟就三个圈 不太想加一整个模块。
