### ISSUE TITLE
【建议】风控增加提示

### ISSUE THREAD

**Issue by Z735803792** [Zeta-qixi/nonebot-plugin-covid19-news#23]
疫情风险地图，合并转发风控则不输出任何信息
![image](https://user-images.githubusercontent.com/70925546/186840555-28e0129f-3170-4835-81e9-8b75ae92c088.png)

**Comment by Zeta-qixi** [comment]
形式是图片还是文字？ 如果是文字可以按着readme改为图片方式发送。
如何图片也不行，那要去cq那边问了，我这边也解决不了。

**Comment by Zeta-qixi** [comment]
新版本已加入风控提示。（但我这边也没风控几次，不知道是不是精确捕获抛出错误）
