### ISSUE TITLE
重启后机器人后报错Failed to import "nonebot_plugin_apscheduler"

### ISSUE THREAD

**Issue by 19231224lhr** [Zeta-qixi/nonebot-plugin-covid19-news#28]
![image](https://user-images.githubusercontent.com/70199004/196857420-58034fd2-b1d4-425a-9d1a-787ae91850f2.png)
![image](https://user-images.githubusercontent.com/70199004/196857470-cfbcad5b-0c83-4020-a97d-10d74bc4b45d.png)
![image](https://user-images.githubusercontent.com/70199004/196857495-a45bcbf9-b635-4d6d-8af1-05219840ec00.png)

**Comment by Zeta-qixi** [comment]
需要更新这个依赖的插件

**Comment by 19231224lhr** [comment]
好啦，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月20日(周四) 中午12:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zeta-qixi/nonebot-plugin-covid19-news] 重启后机器人后报错Failed to import "nonebot_plugin_apscheduler" (Issue #28)
