### ISSUE TITLE
  from nonebot.params import State, CommandArg ModuleNotFoundError: No module named 'nonebot.params'

### ISSUE THREAD

**Issue by Bearlele** [Zeta-qixi/nonebot-plugin-covid19-news#3]
from nonebot.params import State, CommandArg
ModuleNotFoundError: No module named 'nonebot.params'

还有就是我用的是cqhttp 我把nonebot.adapters.onebot改成了nonebot.adapters.cqhttp就可以用了吗

**Comment by Zeta-qixi** [comment]
alpha分支
