### ISSUE TITLE
每隔半小时更新疫情状态时都会进行一次推送

### ISSUE THREAD

**Issue by just1greed** [Zeta-qixi/nonebot-plugin-covid19-news#36]
**状况描述：每隔半小时会重复发送相同的数据**
![image](https://user-images.githubusercontent.com/94421176/203708319-c71a2357-a6b0-4c59-8056-54a71f71ef98.png)

以下是我个人的思考 
https://github.com/Zeta-qixi/nonebot-plugin-covid19-news/blob/395f728eaa93f4bb4d3913828bb4523fa4b194cc/nonebot_plugin_covid19_news/__init__.py#L161-L196
每次更新疫情状态时会调用 update_data() 方法https://github.com/Zeta-qixi/nonebot-plugin-covid19-news/blob/395f728eaa93f4bb4d3913828bb4523fa4b194cc/nonebot_plugin_covid19_news/__init__.py#L172
此方法中会对每个 city 生成一个 Area 类
https://github.com/Zeta-qixi/nonebot-plugin-covid19-news/blob/395f728eaa93f4bb4d3913828bb4523fa4b194cc/nonebot_plugin_covid19_news/tools.py#L75
Area 类中的 isUpdated 属性值默认为True,只有当天无新增时才为false
https://github.com/Zeta-qixi/nonebot-plugin-covid19-news/blob/395f728eaa93f4bb4d3913828bb4523fa4b194cc/nonebot_plugin_covid19_news/tools.py#L20-L24

回到init 发现只要 city 存在且 isUpdated 为True 就发送一次消息推送
https://github.com/Zeta-qixi/nonebot-plugin-covid19-news/blob/395f728eaa93f4bb4d3913828bb4523fa4b194cc/nonebot_plugin_covid19_news/__init__.py#L178-L193
即每次更新疫情状态时，只要该城市当日新增不为0，便会推送一次消息(即使消息并无变化且已多次推送)
由此造成了重复推送

虽然在推送完成后进行了false处理，但是当下次事件触发时仍会 update_data()，isUpdated 属性也会重新被置为True(这也是我不理解的地方)
https://github.com/Zeta-qixi/nonebot-plugin-covid19-news/blob/395f728eaa93f4bb4d3913828bb4523fa4b194cc/nonebot_plugin_covid19_news/__init__.py#L195-L196

以上是我本人的思考，仅代表个人观点，希望作者批评指正，万分感谢

**Comment by just1greed** [comment]
又仔细看了源码 作者考虑的还是比较全面的 对__eq__方法进行了重写 在add方法中判断了数据是否更新，是我没理解就发问了，非常抱歉

现在的疑惑是为何已经进行了数据更新判断，还是会重复发送相同的消息

**Comment by Zeta-qixi** [comment]
最新版本？
有没有频繁重启过？

**Comment by Zeta-qixi** [comment]
我自己调触发时间到一分钟测试。 没有发生这种bug

> 最新版本？
> 有没有频繁重启过？

如果你是热加载调试插件的话 确实会这样。
我调触发时间 1分钟更新一次 ，也是西安，并没有发生这种情况

**Comment by just1greed** [comment]
更新了插件后没有再出现这种情况 感谢作者
