### ISSUE TITLE
增加取关功能？

### ISSUE THREAD

**Issue by aurorataro** [Zeta-qixi/nonebot-plugin-covid19-news#4]

**Comment by Zeta-qixi** [comment]
感谢建议，已添加功能到最新版本，使用方法见readme

**Comment by 19077frb** [comment]
![屏幕截图 2022-02-15 005317](https://user-images.githubusercontent.com/99540587/153909339-e5dab6fe-4118-43c3-aa93-762c3ac07795.png)
readme指令写错了，应该是取消疫情+城市

并且执行后会有如下结果：
![QQ图片20220215005746](https://user-images.githubusercontent.com/99540587/153910693-87f6d629-07b6-4123-aae7-996b28319979.png)
貌似__init__.py第33行unfollow = on_command("取消疫情", priority=5)
改成unfollow = on_command("取消疫情", priority=5, block=True)就好了

**Comment by Zeta-qixi** [comment]
> 

感谢反馈，已处理
