### ISSUE TITLE
插件无法适配

### ISSUE THREAD

**Issue by Reversedeer** [Zeta-qixi/nonebot-plugin-covid19-news#42]
翻了源码看到作者是将插件适配>=v2.0.0rc1吗
我的nonebot版本是v2.0.0b5当初解决了适配问题，但是有时候安装新插件后重启会报错
![(T)(7I%IVKZ{KH K %TL8YS](https://user-images.githubusercontent.com/87823528/208220234-90c15482-6f95-46b2-9895-c4864bab7404.jpg)

**Comment by Zeta-qixi** [comment]
政策改了，目前用的api用不了。已经换了，更新试试。

**Comment by Reversedeer** [comment]
> 政策改了，目前用的api用不了。已经换了，更新试试。

这个和nonebot版本没有关系吗，我的版本低了一个版本

**Comment by Zeta-qixi** [comment]
有关系，nb做了一次破坏性更新，rc和b不兼容。

**Comment by Reversedeer** [comment]
所以我是b5也可以用，但作者要求nonebot>=rc1

**Comment by Zeta-qixi** [comment]
rc1移除了state注入参数 ，查询地方政策的有个指令有影响  比如`广州到上海`。其他指令都没所以不影响。

**Comment by Reversedeer** [comment]
好的，我们这网课都快一月了，但愿早点结束 : )

**Comment by Zeta-qixi** [comment]
`pip install nonebot-plugin-covid19-news==0.7b1` 这个版本应该是适配b1
