### ISSUE TITLE
插件启动失败 AssertionError

### ISSUE THREAD

**Issue by bhshuya** [Zeta-qixi/nonebot-plugin-covid19-news#44]
是不是接口又炸了![image](https://user-images.githubusercontent.com/77972386/209645993-0f4a16af-4d88-4d03-ae4a-0dcf7906ac5f.png)

**Comment by Zeta-qixi** [comment]
应该是的，不再提供数据了

**Comment by Reversedeer** [comment]
网易还有相关数据qwq

**Comment by Reversedeer** [comment]
作者用的是腾讯的api但是前天已经关了，如果我有合适的api填到tools.py也可以吗

**Comment by Zeta-qixi** [comment]
> 作者用的是腾讯的api但是前天已经关了，如果我有合适的api填到tools.py也可以吗

可以哦
